import tensorflow

In [2]:
import tensorflow as tf

check version

In [3]:
tf.version.VERSION

'2.1.0'

building computational graph

In [4]:
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

a =tf.constant(2)
b=tf.constant(3)
c=a+b


In [5]:
print(c)

Tensor("add:0", shape=(), dtype=int32)


running the computational graph

In [6]:
#tf.compat.v1.module contain the complete tensorflow 1.x API, with its original semantics
snn = tf.compat.v1.Session() 
snn.run(c)

5

Example #02

In [7]:
x1 = tf.constant([1,2,4,5])
x2 = tf.constant ([2,3,4,5])

#build graph
# result = tf.multiply(x1,x2)
result = x1*x2

print(result)

Tensor("mul:0", shape=(4,), dtype=int32)


In [8]:
#run the graph
snn.run(result)

array([ 2,  6, 16, 25])

placeholder:
    not providing value at time of declaration but providing value later at time of execution

In [9]:
a = tf.compat.v1.placeholder(tf.float32)
b= tf.compat.v1.placeholder(tf.float32)
c=a+b
print(c)

Tensor("add_1:0", dtype=float32)


In [14]:
snn.run(c,{a:1,b:2}) # assigning value to a and b

3.0

placeholder is very useful when we want to give different input values

In [15]:
snn.run(c, {a:[1,2,3],b:[3,4,5]})


array([4., 6., 8.], dtype=float32)

In [16]:
snn.run(c, {a:[1,2],b:[3,4]})

array([4., 6.], dtype=float32)

Variable

In [21]:

x = tf.compat.v1.Variable([1])

w= tf.compat.v1.Variable([2])

c=x*w
# in tf 1st we initiallize variable

init= tf.compat.v1.global_variables_initializer()
#run that initializer
snn.run(init)
# run the result
snn.run(c)


array([2])