In [39]:
import matplotlib.pyplot as plf
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [40]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.utils import shuffle 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
tf.compat.v1.disable_eager_execution()

In [41]:
df = pd.read_csv('sonar.csv')
df.head(10)

0.02  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
5  0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
6  0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465   
7  0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
8  0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962   
9  0.0039  0.0063  0.0152  0.0336  0.0310  0.0284  0.0396  0.0272  0.0323   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167   0.018  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
5  0.3513  ...  0.0201  0.0248  0.0131  0.0070  0.0138  0.0092  0.0143   
6  0.2838  ...  0.0081  0.0120  0.0045  0.0121  0.0097  0.0085  0.0047   
7  0.1487  ...  0.0145  0.0128  0.0145  0.0058  0.0049  0.0065  0.0093   
8  0.0251  ...  0.0090  0.0223  0.0179  0.0084  0.0068  0.0032  0.0035   
9  0.0452  ...  0.0062  0.0120  0.0052  0.0056  0.0093  0.0042  0.0003   

    0.009  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  
5  0.0036  0.0103  R  
6  0.0048  0.0053  R  
7  0.0059  0.0022  R  
8  0.0056  0.0040  R  
9  0.0053  0.0036  R  

[10 rows x 61 columns]

In [42]:
len(df)

207

In [43]:
len(df.columns)

61

In [44]:
# this data is binary class so

In [45]:
x = df[df.columns[0:60]].values
y = df[df.columns[60]]

In [46]:
x

array([[0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
       [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
       [0.01  , 0.0171, 0.0623, ..., 0.0044, 0.004 , 0.0117],
       ...,
       [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
       [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
       [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]])

In [47]:
y

0      R
1      R
2      R
3      R
4      R
      ..
202    M
203    M
204    M
205    M
206    M
Name: R, Length: 207, dtype: object

In [48]:
# in deep learning algorihtn understand in terms of number

y_labelencoder = LabelEncoder()
y= y_labelencoder.fit_transform(y)

In [49]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
y.shape

(207,)

In [51]:
y = y.reshape(-1,1)

In [52]:
y.shape

(207, 1)

In [53]:
# we doing onehotencoding 
#one hotencoding mean to creat seprate column for each class

In [54]:
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])],     remainder='passthrough')
Y=np.array(columnTransformer.fit_transform(y),dtype=np.int)
    
#onehotencoder = OneHotEncoder(categorical_features='auto')
#Y = onehotencoder.fit_transform(y).toarray()

In [55]:
Y

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0,

In [56]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.20,random_state=42)

print(train_x.shape)
print(test_x.shape)
print(train_y.shape)
print(test_y.shape)

(165, 60)
(42, 60)
(165, 1)
(42, 1)


In [84]:
train_x

array([[0.0856, 0.0454, 0.0382, ..., 0.0102, 0.0037, 0.0037],
       [0.0187, 0.0346, 0.0168, ..., 0.0115, 0.0193, 0.0157],
       [0.0195, 0.0142, 0.0181, ..., 0.0042, 0.0067, 0.0012],
       ...,
       [0.0459, 0.0437, 0.0347, ..., 0.0085, 0.0117, 0.0056],
       [0.031 , 0.0221, 0.0433, ..., 0.0056, 0.0067, 0.0054],
       [0.0162, 0.0253, 0.0262, ..., 0.01  , 0.0048, 0.0019]])

In [57]:
learning_rate =0.01
training_epochs=100
cost_history=np.empty(shape=[1],dtype=float)

In [89]:
#number of output
n_class=2
# set input size
x = tf.compat.v1.placeholder(tf.float32,[None,60])
# initialize weight
w = tf.compat.v1.Variable(tf.zeros([60,n_class]))
# initialize bias
b = tf.compat.v1.Variable(tf.zeros([n_class]))

In [90]:
# initialize all variable
init = tf.compat.v1.global_variables_initializer()

In [91]:
# actual value of output
y= tf.compat.v1.placeholder(tf.float32,[None,n_class])
# prediction
pred = tf.nn.softmax(tf.matmul(x,w)+b)

In [92]:
# calculate error
cost_function = tf.reduce_mean(-tf.reduce_sum(y*tf.math.log(pred)))

In [93]:
# set trianing criteria
training_step = tf.compat.v1.train.GradientDescentOptimizer(learning_rate).minimize(cost_function)

In [94]:
# initialize the session
sess = tf.compat.v1.Session()
sess.run(init)
mse_history=[]

In [96]:
# calculate the cost for each epochs
for i in range(100):
    sess.run(training_step,feed_dict=({x: train_x, y: train_y}))
    cost=sess.run(cost_function,feed_dict={x:train_x,y:train_y})
    cost_history= np.append(cost_history,cost)
    
    
    pred_y = sess.run(pred, feed_dict={x: test_x})
    print('epoch : ',i, '-', 'cost', cost)
    
    mse = tf.reduce_mean(tf.square(pred_y - test_y))
    mse_history.append(sess.run(mse))
    

ValueError: Cannot feed value of shape (165, 60) for Tensor 'Placeholder_11:0', which has shape '(?, 165)'

# Keras

In [99]:
from tensorflow import keras
import numpy as np
from tensorflow.keras import layers

In [103]:
inputs = keras.Input(shape=(60,))

In [104]:
inputs.shape

TensorShape([Dimension(None), Dimension(60)])

In [106]:
inputs.dtype

tf.float32

# functional api

In [112]:
x = inputs
dense = layers.Dense(60, activation="sigmoid")(x)
outputs=layers.Dense(2)(dense)

In [120]:
model_funct = keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")

In [121]:
model_funct.summary()

Model: "mnist_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 60)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 60)                3660      
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 122       
Total params: 3,782
Trainable params: 3,782
Non-trainable params: 0
_________________________________________________________________


In [124]:
keras.utils.plot_model(model_funct, "my_first_model.png")

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [127]:
model_funct.build()

TypeError: build() missing 1 required positional argument: 'input_shape'

In [ ]:

model_funct.compile(optimizer="adam", loss="mse")

In [122]:
model_seq = keras.Sequential()
model_seq.add(keras.Input(shape=(60,)))
model_seq.add(layers.Dense(60, activation="sigmoid"))
model_seq.add(layers.Dense(2, activation="sigmoid"))

In [123]:
model_seq.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 60)                3660      
_________________________________________________________________
dense_10 (Dense)             (None, 2)                 122       
Total params: 3,782
Trainable params: 3,782
Non-trainable params: 0
_________________________________________________________________


In [125]:
keras.utils.plot_model(model_seq, "my_first_model.png")

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [126]:
keras.utils.plot_model(model_seq, "my_first_model_with_shape_info.png", show_shapes=True)


('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [ ]:
model.compile(optimizer="adam", loss="mse")